# Generated by Django 3.0.3 on 2020-03-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoCode', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('expiryDate', models.DateField()),
            ],
        ),
    ]
