# Generated by Django 3.0.3 on 2020-03-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_auto_20200317_1219'),
        ('movie', '0001_initial'),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shows',
            new_name='Show',
        ),
    ]
