# Generated by Django 3.0.3 on 2020-03-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contactNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
