# Generated by Django 3.0.3 on 2020-03-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='contactNumber',
            field=models.CharField(max_length=20),
        ),
    ]
